<?php

/**
*
* Commentaire
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Commentaire extends Entity {
    public $texte;     // varchar(255)
    public $medias;     // varchar(255)
    public $id_user;     // int
    public $id_recette;     // int
    public $recette_user_id;     // int

    public function __construct(
        $texte = "",
        $medias = "",
        $id_user = "",
        $id_recette = "",
        $recette_user_id = "",
    $id = false) {
        parent::__construct($id);

        $this->texte = $texte;
        $this->medias = $medias;
        $this->id_user = $id_user;
        $this->id_recette = $id_recette;
        $this->recette_user_id = $recette_user_id;
    }
}
?>
