<?php

/**
*
* Contient
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Contient extends Entity {
    public $recette_id;     // int
    public $ingredient_id;     // int
    public $quantite;     // int

    public function __construct(
        $recette_id = "",
        $ingredient_id = "",
        $quantite = "",
    $id = false) {
        parent::__construct($id);

        $this->recette_id = $recette_id;
        $this->ingredient_id = $ingredient_id;
        $this->quantite = $quantite;
    }
}
?>
