<?php

/**
*
* Possede
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Possede extends Entity {
    public $recette_id;     // int
    public $recette_user_id;     // int
    public $tag_id;     // int

    public function __construct(
        $recette_id = "",
        $recette_user_id = "",
        $tag_id = "",
    $id = false) {
        parent::__construct($id);

        $this->recette_id = $recette_id;
        $this->recette_user_id = $recette_user_id;
        $this->tag_id = $tag_id;
    }
}
?>
