<?php

/**
*
* Recette
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Recette extends Entity {
    public $nom;     // varchar(255)
    public $etapes;     // varchar(255)
    public $categorie;     // varchar(45)
    public $temps;     // varchar(255)
    public $budget;     // varchar(255)
    public $medias;     // varchar(45)
    public $id_user;     // int

    public function __construct(
        $nom = "",
        $etapes = "",
        $categorie = "",
        $temps = "",
        $budget = "",
        $medias = "",
        $id_user = "",
    $id = false) {
        parent::__construct($id);

        $this->nom = $nom;
        $this->etapes = $etapes;
        $this->categorie = $categorie;
        $this->temps = $temps;
        $this->budget = $budget;
        $this->medias = $medias;
        $this->id_user = $id_user;
    }
}
?>
