<?php

/**
*
* User
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class User extends Entity {
    public $login;     // varchar(255)
    public $mdp;     // varchar(255)
    public $mail;     // varchar(45)
    public $nom;     // varchar(45)
    public $prenom;     // varchar(45)
    public $age;     // int
    public $cookie;     // varchar(255)

    public function __construct(
        $login = "",
        $mdp = "",
        $mail = "",
        $nom = "",
        $prenom = "",
        $age = "",
        $cookie = "",
    $id = false) {
        parent::__construct($id);

        $this->login = $login;
        $this->mdp = $mdp;
        $this->mail = $mail;
        $this->nom = $nom;
        $this->prenom = $prenom;
        $this->age = $age;
        $this->cookie = $cookie;
    }
}
?>
