<?php

/**
*
* User
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class User extends Entity {
    public $login;     // varchar(255)
    public $email;     // varchar(255)
    public $password;     // varchar(255)
    public $cookie;     // varchar(255)

    public function __construct(
        $login = "",
        $email = "",
        $password = "",
        $cookie = "",
    $id = false) {
        parent::__construct($id);

        $this->login = $login;
        $this->email = $email;
        $this->password = $password;
        $this->cookie = $cookie;
    }
}
?>
