<?php

/**
*
* PossedeSQL
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Queries;

use Helpers\DB\Query;

class  PossedeSQL extends Query {
}
?>
