user:
  login: varchar(255)
  mdp: varchar(255)
  mail: varchar(45)
  nom: varchar(45)
  prenom: varchar(45)
  age: int
  cookie: varchar(255)
    
commentaire:
  texte: varchar(255)
  medias: varchar(255)
  id_user: int
  id_recette: int
  recette_user_id: int 

recette:
  nom: varchar(255)
  etapes: varchar(255)
  categorie: varchar(45)
  temps: varchar(255)
  budget: varchar(255)
  medias: varchar(45)
  id_user: int
  
contient: 
  recette_id: int
  ingredient_id: int
  quantite: int
 
ingredient:
  nom: varchar(45)
  type: varchar(45)
  
possede: 
  recette_id: int
  recette_user_id: int
  tag_id: int
  
tag: 
  nom: varchar(255)